[package]
name = "hyperbutt-rs"
version = "0.1.0"
authors = ["a <b@c>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
multiboot2 = "*"

[features]
boot-multiboot = []
boot-uefi = []
